sveltejs/svelte-eslint-parser

src/parser/index.ts, src/parser/script.ts, tests/fixtures/parser/ast/reactive-with-var01-input.svelte, tests/fixtures/parser/ast/reactive-with-var01-output.json, tests/fixtures/parser/ast/reactive-with-var01-prefer-const-result.json, tests/fixtures/parser/ast/reactive-with-var01-scope-output.json
=> Fix incorrect scope for reactive statement with predefined variables.

src/parser/analyze-scope.ts, tests/fixtures/parser/ast/$var-no-unused-vars-result.json, tests/fixtures/parser/ast/$var-scope-output.json, tests/fixtures/parser/ast/unused-write-only-store-no-unused-vars-result.json, tests/fixtures/parser/ast/unused-write-only-store-scope-output.json
This prevents false positives of no-unused-vars.
=> Add virtual reference to a used store

src/parser/index.ts, tests/fixtures/parser/ast/reactive-with-store01-input.svelte, tests/fixtures/parser/ast/reactive-with-store01-output.json, tests/fixtures/parser/ast/reactive-with-store01-scope-output.json, tests/fixtures/parser/ast/reactive-with-store02-input.svelte, tests/fixtures/parser/ast/reactive-with-store02-output.json, tests/fixtures/parser/ast/reactive-with-store02-scope-output.json
=> Fix incorrect scope analysis for reactive stores

src/parser/converts/element.ts, tests/fixtures/parser/ast/docs/template-syntax/15_1-svelte-component/02-output.json, tests/fixtures/parser/ast/docs/template-syntax/15_2-svelte-element/02-output.json, tests/fixtures/parser/ast/svelte-element-with-bind-this-output.json, tests/fixtures/parser/ast/this-attr01-input.svelte, tests/fixtures/parser/ast/this-attr01-output.json, tests/fixtures/parser/ast/this-attr01-scope-output.json, tests/fixtures/parser/ast/this-attr02-input.svelte, tests/fixtures/parser/ast/this-attr02-output.json, tests/fixtures/parser/ast/this-attr02-scope-output.json, tests/fixtures/parser/ast/this-attr03-input.svelte, tests/fixtures/parser/ast/this-attr03-output.json, tests/fixtures/parser/ast/this-attr03-scope-output.json
This PR fixes the order of the `this` property.
```svelte
<svelte:component
this={foo} 
/>
```
Previously it was always placed at the end of the attributes array.
=> Fix the order of `this` property

.github/workflows/GHPages.yml
This PR modifies the workflow to deploy to GitHub Pages without using the gh-pages branch.
See https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/
Note: We need to change the settings before merging it.
=> Chore: Use GitHub Pages Custom GitHub Actions Workflows

.changeset/grumpy-avocados-behave.md, src/context/script-let.ts, tests/fixtures/parser/ast/ts-store01-type-output.svelte, tests/fixtures/parser/ast/ts-store02-type-output.svelte, tests/fixtures/parser/ast/ts-store03-input.svelte, tests/fixtures/parser/ast/ts-store03-no-unused-expressions-result.json, tests/fixtures/parser/ast/ts-store03-output.json, tests/fixtures/parser/ast/ts-store03-requirements.json, tests/fixtures/parser/ast/ts-store03-scope-output.json, tests/fixtures/parser/ast/ts-store03-type-output.svelte, tests/fixtures/tsconfig.test.json
close https://github.com/ota-meshi/eslint-plugin-svelte/issues/242
=> fix: wrong store access type information

.changeset/long-rabbits-remain.md, src/parser/analyze-type/index.ts, tests/fixtures/parser/ast/ts-not-reactive01-input.svelte, tests/fixtures/parser/ast/ts-not-reactive01-output.json, tests/fixtures/parser/ast/ts-not-reactive01-scope-output.json, tests/fixtures/parser/ast/ts-not-reactive01-type-output.svelte
=> Fix error in member expr on LHS of reactive statement with TS

.changeset/sweet-boats-exist.md, src/parser/converts/element.ts, src/parser/html.ts, tests/fixtures/parser/ast/script-tag-input.svelte, tests/fixtures/parser/ast/script-tag-output.json, tests/fixtures/parser/ast/script-tag-scope-output.json, tests/src/parser/__snapshots__/html.ts.snap, tests/src/parser/html.ts
=> fix: parsing error when `<script>` has attribute with empty value

.changeset/chilly-experts-reply.md, src/context/script-let.ts, src/parser/converts/attr.ts, tests/fixtures/parser/ast/ts-shorthand-attr01-input.svelte, tests/fixtures/parser/ast/ts-shorthand-attr01-output.json, tests/fixtures/parser/ast/ts-shorthand-attr01-scope-output.json, tests/fixtures/parser/ast/ts-shorthand-attr01-type-output.svelte, tools/update-fixtures.ts
close https://github.com/ota-meshi/eslint-plugin-svelte/issues/278
=> fix: missing ts node for key of shorthand attribute

.changeset/angry-pumpkins-ring.md, src/context/let-directive-collection.ts, src/context/script-let.ts, src/parser/converts/block.ts, src/parser/converts/element.ts, src/parser/index.ts, src/parser/sort.ts, src/parser/template.ts, tests/fixtures/parser/ast/docs/template-syntax/13-slot/03-slot-let-name-value/01-scope-output.json, tests/fixtures/parser/ast/let-directive03-input.svelte, tests/fixtures/parser/ast/let-directive03-output.json, tests/fixtures/parser/ast/let-directive03-scope-output.json, tests/src/parser/parser.ts, tools/update-fixtures.ts
related to https://github.com/ota-meshi/eslint-plugin-svelte/issues/356
=> fix: wrong variable scope in let directive

.changeset/modern-spiders-retire.md, src/context/script-let.ts, src/parser/converts/root.ts, tests/src/scope/scope.ts
Fixes #280.
Related to #291.
This change corrects the result of `context.getScope()`, but it is a breaking change.
=> fix: resolve to module scope for top level statements

.changeset/violet-buses-tickle.md, explorer-v2/src/lib/VirtualScriptCode.svelte, src/context/script-let.ts, src/parser/converts/attr.ts, src/parser/converts/element.ts, src/scope/index.ts, tests/fixtures/parser/ast/ts-event02-type-output.svelte, tests/fixtures/parser/ast/ts-event03-input.svelte, tests/fixtures/parser/ast/ts-event03-no-unused-expressions-result.json, tests/fixtures/parser/ast/ts-event03-output.json, tests/fixtures/parser/ast/ts-event03-requirements.json, tests/fixtures/parser/ast/ts-event03-scope-output.json, tests/fixtures/parser/ast/ts-event03-type-output.svelte, tests/fixtures/parser/ast/ts-event04-input.svelte, tests/fixtures/parser/ast/ts-event04-no-unused-expressions-result.json, tests/fixtures/parser/ast/ts-event04-output.json, tests/fixtures/parser/ast/ts-event04-scope-output.json, tests/fixtures/parser/ast/ts-event04-type-output.svelte, tests/fixtures/parser/ast/ts-event05-input.svelte, tests/fixtures/parser/ast/ts-event05-no-unused-expressions-result.json, tests/fixtures/parser/ast/ts-event05-output.json, tests/fixtures/parser/ast/ts-event05-scope-output.json, tests/fixtures/parser/ast/ts-event05-type-output.svelte, tools/update-fixtures.ts
Related to https://github.com/ota-meshi/eslint-plugin-svelte/issues/390
=> feat: improved event handler type

.changeset/config.json, .changeset/two-lamps-behave.md, .github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, docs/internal-mechanism.md, explorer-v2/src/lib/Header.svelte, explorer-v2/src/lib/SnsBar.svelte, package.json, src/parser/typescript/analyze/index.ts, src/parser/typescript/context.ts, tests/fixtures/integrations/type-info-tests/reactive2-input.svelte
This PR fixes the link as the repository moves.
=> chore: move repo

.github/workflows/NodeCI.yml
I just realized we didn't add those tests 😅
=> chore(actions): add test for nodejs v18, v19

.changeset/itchy-toes-tell.md, src/parser/converts/common.ts, src/parser/converts/element.ts, src/parser/svelte-ast-types.ts, tests/fixtures/parser/ast/this-attr04-input.svelte, tests/fixtures/parser/ast/this-attr04-output.json, tests/fixtures/parser/ast/this-attr04-scope-output.json
fixes https://github.com/sveltejs/eslint-plugin-svelte/issues/437
=> fix: crash with plain `this` attribute.

.changeset/clean-taxis-rule.md, package.json, src/parser/converts/attr.ts, tests/fixtures/integrations/parser-object-tests/ts-multiple-parser-setup.ts, tests/fixtures/integrations/parser-object-tests/ts-single-parser-setup.ts, tests/fixtures/integrations/type-info-tests/await-setup.ts, tests/fixtures/integrations/type-info-tests/i18n-setup.ts, tests/fixtures/integrations/type-info-tests/issue226-setup.ts, tests/fixtures/integrations/type-info-tests/no-unnecessary-condition01-setup.ts, tests/fixtures/integrations/type-info-tests/plugin-issue254-setup.ts, tests/fixtures/integrations/type-info-tests/reactive-setup.ts, tests/fixtures/integrations/type-info-tests/reactive2-setup.ts, tests/fixtures/integrations/type-info-tests/ts-newline-setup.ts, tests/fixtures/integrations/type-info-tests/ts-no-misused-promises-setup.ts, tests/fixtures/parser/ast/ts-event05-input.svelte, tests/fixtures/parser/ast/ts-event05-type-output.svelte, tests/fixtures/parser/ast/ts-event06-config.json, tests/fixtures/parser/ast/ts-event06-input.svelte, tests/fixtures/parser/ast/ts-event06-no-unused-expressions-result.json, tests/fixtures/parser/ast/ts-event06-output.json, tests/fixtures/parser/ast/ts-event06-scope-output.json, tests/fixtures/parser/ast/ts-event06-type-output.svelte, tests/src/integrations.ts, tests/src/parser/error.ts, tests/src/parser/eslint-rules.ts, tests/src/parser/eslint.ts, tests/src/parser/parser.ts, tests/src/parser/test-utils.ts, tests/src/parser/typescript/index.ts, tools/update-fixtures.ts
Related to https://github.com/sveltejs/eslint-plugin-svelte/issues/432
This PR improves assigning the correct event handler type when the component type is available.
However, since `@typescript-eslint/parser` cannot be used to retrieve component types, users should use the experimental parser `typescript-eslint-parser-for-extra-files` instead. .
If the user is using `@typescript-eslint/parser` it will be the same as before.
=> feat: improve component event handler type

.changeset/wet-lizards-reflect.md, src/context/script-let.ts, src/parser/converts/attr.ts, tests/fixtures/parser/ast/ts-use01-input.svelte, tests/fixtures/parser/ast/ts-use01-no-unused-expressions-result.json, tests/fixtures/parser/ast/ts-use01-no-unused-vars-result.json, tests/fixtures/parser/ast/ts-use01-output.json, tests/fixtures/parser/ast/ts-use01-scope-output.json, tests/fixtures/parser/ast/ts-use01-type-output.svelte
This PR improves assigning the correct type to `use:` directive parameters.
Related to https://github.com/sveltejs/eslint-plugin-svelte/issues/442
=> feat: support for `use:` directive parameter type

.changeset/two-months-yawn.md, .github/workflows/NodeCI.yml, explorer-v2/src/lib/Header.svelte, package.json, tests/fixtures/parser/ast/ts-event03-type-output.svelte, tests/fixtures/parser/ast/ts-reactive02-type-output.svelte, tests/fixtures/parser/ast/ts-reactive05-type-output.svelte, tests/fixtures/parser/ast/ts-store01-type-output.svelte, tests/fixtures/parser/ast/ts-store02-type-output.svelte
Related to https://github.com/sveltejs/eslint-plugin-svelte/issues/449
=> feat: add experimental support for Svelte v4

.changeset/curly-turkeys-appear.md, src/context/script-let.ts, tests/fixtures/parser/ast/at-const01-within-component-input.svelte, tests/fixtures/parser/ast/at-const01-within-component-output.json, tests/fixtures/parser/ast/at-const01-within-component-scope-output.json
=> fix: crash when using component and `{@const}`

package.json, tests/fixtures/parser/style-context/empty-style-element-output.json, tests/fixtures/parser/style-context/one-line-css-output.json, tests/fixtures/parser/style-context/parse-error-output.json, tests/fixtures/parser/style-context/simple-css-output.json, tests/fixtures/parser/style-context/simple-scss-output.json, tests/fixtures/parser/style-context/unrelated-style-attr-output.json
I created this PR because `eco-system-ci` is failed.
https://github.com/sveltejs/svelte-ecosystem-ci/actions/runs/5483027087/jobs/9994935125
After investigation, I found that this was due to a change in the order of JSON properties when postcss 8.4.25 was released.
I think we can not say that this was not a bug, so I simply upgraded the postcss version and fixed tests.
=> chore: update PostCSS and tests

.changeset/grumpy-dolphins-pay.md, explorer-v2/package.json, package.json, src/parser/converts/attr.ts, src/parser/converts/mustache.ts, src/utils/index.ts, tests/fixtures/parser/ast/svelte5/ts-event07-input.svelte, tests/fixtures/parser/ast/svelte5/ts-event07-no-unused-vars-result.json, tests/fixtures/parser/ast/svelte5/ts-event07-output.json, tests/fixtures/parser/ast/svelte5/ts-event07-requirements.json, tests/fixtures/parser/ast/svelte5/ts-event07-scope-output.json, tests/fixtures/parser/ast/svelte5/ts-event07-type-output.svelte, tests/fixtures/parser/ast/svelte5/ts-event08-input.svelte, tests/fixtures/parser/ast/svelte5/ts-event08-output.json, tests/fixtures/parser/ast/svelte5/ts-event08-scope-output.json, tests/fixtures/parser/ast/svelte5/ts-event08-type-output.svelte, tests/fixtures/parser/ast/svelte5/ts-snippet01-input.svelte, tests/fixtures/parser/ast/svelte5/ts-snippet01-output.json, tests/fixtures/parser/ast/svelte5/ts-snippet01-prefer-const-result.json, tests/fixtures/parser/ast/svelte5/ts-snippet01-scope-output.json, tests/fixtures/parser/ast/svelte5/ts-snippet01-type-output.svelte
TODO
Discussion point:
I think somehow we can avoid to generate injection types if there is type information but I couldn't find a way. If we can do this, this is better in terms of performance.
=> feat: Skip type injection if template uses TypeScript

.eslintrc.js, src/parser/converts/element.ts, src/parser/typescript/analyze/index.ts, src/scope/index.ts, tests/src/parser/test-utils.ts
I've been using `complexity` for a long time, but since you often need to suppress rules to do type guarding well using typescript, I thought it would be better to turn this rule off.
=> chore: turn off eslint complexity rule

.changeset/eighty-books-study.md, .github/workflows/NodeCI.yml, src/context/script-let.ts
We can not merge https://github.com/sveltejs/svelte-eslint-parser/pull/399 if we continue to support `@typescript-eslint` v4.
`@typescript-eslint` v5 was released on October 12, 2021. (https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0)
The number of v4 downloads is 1.9% of v6 downloads, but I believe that many of those are CIs from ecosystems such as ours.
We can merge https://github.com/sveltejs/svelte-eslint-parser/pull/399 after merge this PR.
=> chore: drop `@typescript-eslint` v4 support

.changeset/yellow-hornets-bow.md, docs/AST.md, package.json, src/ast/html.ts, src/context/script-let.ts, src/parser/converts/block.ts, src/parser/converts/render.ts, src/parser/svelte-ast-types.ts, src/visitor-keys.ts, tests/fixtures/parser/ast/svelte5/docs/snippets/01-output.json, tests/fixtures/parser/ast/svelte5/docs/snippets/01-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/snippets/02-output.json, tests/fixtures/parser/ast/svelte5/docs/snippets/03-snippet-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/snippets/04-snippet-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/snippets/05-snippet-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/snippets/06-passing-snippets-to-components-output.json, tests/fixtures/parser/ast/svelte5/docs/snippets/07-passing-snippets-to-components-output.json, tests/fixtures/parser/ast/svelte5/docs/snippets/09-passing-snippets-to-components-output.json, tests/fixtures/parser/ast/svelte5/render01-input.svelte, tests/fixtures/parser/ast/svelte5/render01-output.json, tests/fixtures/parser/ast/svelte5/render01-scope-output.json, tests/fixtures/parser/ast/svelte5/ts-snippet01-output.json, tests/fixtures/parser/ast/svelte5/ts-snippet01-type-output.svelte
related to https://github.com/sveltejs/eslint-plugin-svelte/issues/686
=> feat: change AST of `{@render}` and `{#snippet}` to match the latest version of svelte v5.

.changeset/loud-geese-trade.md, src/context/index.ts, src/context/script-let.ts, src/parser/compat.ts, src/parser/converts/attr.ts, src/parser/converts/block.ts, src/parser/converts/const.ts, src/parser/converts/element.ts, src/parser/converts/mustache.ts, src/parser/converts/render.ts, src/parser/converts/root.ts, src/parser/converts/text.ts, src/parser/espree.ts, src/parser/html.ts, src/parser/index.ts, src/parser/svelte-ast-types.ts, src/parser/template.ts, tests/fixtures/parser/ast/at-const02-input.svelte, tests/fixtures/parser/ast/at-const02-output.json, tests/fixtures/parser/ast/at-const02-scope-output.json, tests/fixtures/parser/ast/await03-requirements.json, tests/src/parser/__snapshots__/html.ts.snap, tests/src/parser/html.ts, tests/src/parser/test-utils.ts, tests/src/parser/typescript/assert-result.ts
This PR will be changed to also use Svelte v5's modern AST.
I believe this has performance benefits as it allows we to skip the transformation step to legacy AST.
=> feat: change it to use modern AST, if svelte v5 is installed

README.md
I would like to release eslint-plugin-svelte v2.36.0.
In preparation for the release, this PR clarifies in the documentation that support for Svelte v5 is not yet stable.
https://github.com/sveltejs/eslint-plugin-svelte/issues/727
=> docs: add note for svelte v5

.changeset/violet-rockets-relax.md, src/context/script-let.ts, tests/fixtures/parser/ast/svelte5/docs/runes/11-1-$inspect-ts-output.json, tests/fixtures/parser/ast/svelte5/docs/runes/11-2-$inspect-ts-output.json, tests/fixtures/parser/ast/svelte5/ts-$derived-by01-output.json, tests/fixtures/parser/ast/svelte5/ts-$derived01-output.json, tests/fixtures/parser/ast/svelte5/ts-$effect01-output.json, tests/fixtures/parser/ast/svelte5/ts-$effectpre01-output.json, tests/fixtures/parser/ast/ts-tokens-bug-input.svelte, tests/fixtures/parser/ast/ts-tokens-bug-no-undef-result.json, tests/fixtures/parser/ast/ts-tokens-bug-output.json, tests/fixtures/parser/ast/ts-tokens-bug-scope-output.json, tests/src/parser/typescript/index.ts
=> fix: wrong token when using `lang=ts`

.changeset/kind-houses-work.md, src/parser/analyze-scope.ts, src/parser/index.ts, tests/fixtures/parser/ast/svelte5/$bindable-used-input.svelte, tests/fixtures/parser/ast/svelte5/$bindable-used-output.json, tests/fixtures/parser/ast/svelte5/$bindable-used-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-2-$bindable-no-unused-vars-result.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-2-$bindable-prefer-const-result.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-2-$bindable-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-3-$bindable-no-unused-vars-result.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-3-$bindable-prefer-const-result.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-4-$bindable-ts-no-unused-vars-result.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-4-$bindable-ts-prefer-const-result.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-4-$bindable-ts-scope-output.json
This PR will give the `$bindable()` prop a virtual reference, letting ESLint rules know that it's a two-way bound variable.
---
See https://github.com/sveltejs/eslint-plugin-svelte/issues/768
=> feat: add support for `$bindable()` scope analysis

.changeset/shy-cups-visit.md, README.md, src/index.ts, src/parser/analyze-scope.ts, src/parser/globals.ts, src/parser/index.ts, src/parser/parser-options.ts, src/parser/svelte-parse-context.ts, src/parser/svelte-version.ts, src/parser/typescript/analyze/index.ts, src/parser/typescript/index.ts, src/scope/index.ts, src/svelte-config/index.ts, src/svelte-config/parser.ts, tests/fixtures/parser/ast/svelte.config.js, tests/fixtures/parser/ast/svelte5/$props-without-runes01-config.json, tests/fixtures/parser/ast/svelte5/$props-without-runes01-input.svelte, tests/fixtures/parser/ast/svelte5/$props-without-runes01-no-undef-result.json, tests/fixtures/parser/ast/svelte5/$props-without-runes01-output.json, tests/fixtures/parser/ast/svelte5/$props-without-runes01-scope-output.json, tests/fixtures/parser/ast/svelte5/$props-without-runes02-config.json, tests/fixtures/parser/ast/svelte5/$props-without-runes02-input.svelte, tests/fixtures/parser/ast/svelte5/$props-without-runes02-no-undef-result.json, tests/fixtures/parser/ast/svelte5/$props-without-runes02-output.json, tests/fixtures/parser/ast/svelte5/$props-without-runes02-scope-output.json, tests/fixtures/parser/ast/svelte5/svelte-options02-input.svelte, tests/fixtures/parser/ast/svelte5/svelte-options02-output.json, tests/fixtures/parser/ast/svelte5/svelte-options02-scope-output.json, tests/src/parser/typescript/index.ts, tests/src/svelte-config/parser.ts
related to #423
This PR changes the parser to allow opt-in/out of Rune parsing. (However, it requires Svelte v5.)
The main changes are:
- Added a new option `svelteFeatures.runes` to control whether runes are parsed.
- Added a new option `parserOptions.svelteConfig` to specify `svelte.config.js`.
If not specified, some config will be statically parsed from the `svelte.config.js` file.
- If there is no option in `svelteFeatures.runes`, it will read the `compilerOptions.runes` in `svelte.config.js`.
- If `<svelte:options runes={...}>` is present, it determines whether to prioritize them and parse Runes.
- Change the parser service to provide `svelteParseContext`, to make that information available to the eslint-plugin.
- ~~I think the next issue can be solved by telling the compiler whether …
=> feat: makes it optional whether to parse runes.

.changeset/brave-penguins-compete.md, README.md, src/parser/parser-options.ts, src/parser/svelte-parse-context.ts, tests/fixtures/parser/ast/svelte5/$props-without-runes02-config.json
Follow up of https://github.com/sveltejs/svelte-eslint-parser/pull/536#issuecomment-2173326926
=> fix: set `svelteFeatures.runes` to `true` by default for Svelte 5

.changeset/young-clouds-fly.md, src/context/script-let.ts, src/parser/converts/block.ts, tests/fixtures/parser/ast/svelte5/snippet02-nesting-input.svelte, tests/fixtures/parser/ast/svelte5/snippet02-nesting-output.json, tests/fixtures/parser/ast/svelte5/snippet02-nesting-scope-output.json
=> fix: parsing error for nesting `{#snippet}`

.changeset/new-rats-sneeze.md, package.json, src/context/index.ts, src/parser/compat.ts, src/parser/converts/attr.ts, src/parser/converts/block.ts, src/parser/converts/const.ts, src/parser/converts/element.ts, src/parser/converts/mustache.ts, src/parser/converts/render.ts, src/parser/converts/root.ts, src/parser/html.ts, src/parser/index.ts, src/parser/svelte-ast-types-for-v5.ts, src/parser/svelte-parse-context.ts, src/parser/template.ts, tests/fixtures/parser/ast/svelte5/docs/snippets/10-typing-snippets-type-output.svelte, tests/fixtures/parser/ast/svelte5/docs/snippets/11-typing-snippets-type-output.svelte, tests/fixtures/parser/ast/svelte5/generics01-snippets-type-output.svelte
This PR updates the svelte version and fixes the wrong location and token of `{:else if}` nodes when using the updated svelte.
Also, since Svelte no longer provides types for AST nodes, I have added code to work around that.
=> fix: update svelte to 5.0.0-next.181 and fix for `{:else if}`

.changeset/chilly-dolls-push.md, package.json, src/parser/converts/attr.ts, src/parser/svelte-ast-types.ts
related to https://github.com/sveltejs/eslint-plugin-svelte/issues/826
=> feat: support for svelte 5.0.0-next.191

.changeset/late-poems-collect.md, src/svelte-config/parser.ts, tests/src/svelte-config/parser.ts
fixes https://github.com/sveltejs/eslint-plugin-svelte/issues/849
=> fix: incorrect runes inference when having empty compiler options

.changeset/early-lobsters-repeat.md, src/parser/converts/attr.ts, tests/fixtures/parser/ast/svelte5/ts-event06-type-output.svelte
=> feat: improve props type

.changeset/wise-mice-hang.md, src/parser/converts/block.ts, tests/fixtures/parser/ast/svelte5/ts-snippet03-input.svelte, tests/fixtures/parser/ast/svelte5/ts-snippet03-output.json, tests/fixtures/parser/ast/svelte5/ts-snippet03-scope-output.json
related to https://github.com/sveltejs/eslint-plugin-svelte/issues/872
=> fix: error in snippets with type annotations

tests/fixtures/parser/ast/ts-slot-binding01-config.json, tests/fixtures/parser/ast/ts-slot-binding01-input-child.svelte, tests/fixtures/parser/ast/ts-slot-binding01-input.svelte, tests/fixtures/parser/ast/ts-slot-binding01-output.json, tests/fixtures/parser/ast/ts-slot-binding01-requirements.json, tests/fixtures/parser/ast/ts-slot-binding01-scope-output-svelte5.json, tests/fixtures/parser/ast/ts-slot-binding01-scope-output.json, tests/fixtures/parser/ast/ts-slot-binding01-sveltev4-input-child.svelte, tests/fixtures/parser/ast/ts-slot-binding01-sveltev4-input.svelte, tests/fixtures/parser/ast/ts-slot-binding01-sveltev4-output.json, tests/fixtures/parser/ast/ts-slot-binding01-sveltev4-requirements.json, tests/fixtures/parser/ast/ts-slot-binding01-sveltev4-scope-output.json, tests/fixtures/parser/ast/ts-slot-binding01-sveltev4-type-output.svelte, tests/fixtures/parser/ast/ts-slot-binding01-type-output.svelte
close: https://github.com/sveltejs/svelte-eslint-parser/issues/564
I confirmed slot binding is works as expected in Svelte5 but not in Svelte4.
I just added tests for this.
=> chore: add tests for slot binding

.changeset/witty-hairs-judge.md, package.json, src/ast/html.ts, src/context/script-let.ts, src/parser/converts/block.ts, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/01-each-blocks-without-an-item-input.svelte, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/01-each-blocks-without-an-item-no-undef-result.json, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/01-each-blocks-without-an-item-output.json, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/01-each-blocks-without-an-item-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/02-each-blocks-without-an-item-input.svelte, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/02-each-blocks-without-an-item-no-undef-result.json, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/02-each-blocks-without-an-item-no-unused-vars-result.json, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/02-each-blocks-without-an-item-output.json, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/02-each-blocks-without-an-item-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/03-each-blocks-without-an-item-input.svelte, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/03-each-blocks-without-an-item-output.json, tests/fixtures/parser/ast/svelte5/docs/template-syntax/03-each/03-each-blocks-without-an-item-scope-output.json
See also https://github.com/sveltejs/svelte/releases/tag/svelte%405.4.0 and https://svelte.dev/docs/svelte/each#Each-blocks-without-an-item
=> feat: add support `{#each}` without `as` (svelte v5.4.0)

.changeset/smart-rats-decide.md, src/svelte-config/index.ts
Part of https://github.com/sveltejs/eslint-plugin-svelte/issues/905
Svelte5 added `warningFilter` to filter warnings as universal way.
https://svelte.dev/docs/svelte/svelte-compiler#ModuleCompileOptions
=> feat: Add `warningFilter` to `SvelteConfig`

.changeset/sharp-guests-sniff.md, src/context/index.ts, tests/fixtures/parser/ast/at-html01-input.svelte, tests/fixtures/parser/ast/at-html01-output.json, tests/fixtures/parser/ast/at-html01-scope-output.json
close: https://github.com/sveltejs/svelte-eslint-parser/issues/631
=> fix: do not throw error if `<script>` exists inside `{@html}`

.changeset/brown-owls-bow.md, src/parser/index.ts, src/parser/svelte-parse-context.ts
This PR corrects the approach used in #633, where static analysis relied on the AST of the template section to detect runes, which was entirely unnecessary. The new implementation performs static analysis on the final AST instead.
=> fix: correct detection of runes mode in parsed files

.changeset/empty-turtles-report.md, src/parser/analyze-scope.ts, src/parser/globals.ts, src/parser/typescript/analyze/index.ts, tests/fixtures/parser/ast/svelte5/unknown-runes-mode/$props-input.svelte, tests/fixtures/parser/ast/svelte5/unknown-runes-mode/$props-output.json, tests/fixtures/parser/ast/svelte5/unknown-runes-mode/$props-scope-output.json, tests/fixtures/parser/ast/svelte5/unknown-runes-mode/svelte.config.js
Fixed: https://github.com/sveltejs/svelte-eslint-parser/pull/633#issuecomment-2586185087
Before #633, the default value was set to `true` when it was unclear whether the file was in Runes mode. However, this approach could cause `eslint-plugin-svelte` to malfunction if the file was not in Runes mode. The behavior was changed to return `undefined` when the mode was uncertain to address this. Unfortunately, this caused issues in parts of the parser that rely on Runes. This PR fixes that bug.
~~I want to add a test for this, but I’m not sure how to do it. 😅~~
-> I added a test and I confirmed that this test is failed without changes.👍
=> fix: resolve issues in Runes mode detection causing parser malfunctions

.changeset/lovely-crabs-return.md, package.json, src/ast/html.ts, src/parser/converts/const.ts, src/visitor-keys.ts, tests/fixtures/parser/ast/at-const01-within-component-output.json, tests/fixtures/parser/ast/at-const02-output.json, tests/fixtures/parser/ast/at-const02-scope-output.json, tests/fixtures/parser/ast/docs/template-syntax/10.1-at-const/01-output.json, tests/fixtures/parser/ast/docs/template-syntax/10.1-at-const/02-output.json, tests/fixtures/parser/ast/docs/template-syntax/10.1-at-const/02-scope-output.json
See https://github.com/sveltejs/svelte-eslint-parser/pull/620#issuecomment-2589050203
close #620
=> feat: replace `declaration` property of SvelteConstTag with `declarations` property

.changeset/stale-birds-win.md, src/parser/typescript/analyze/index.ts, tests/fixtures/parser/ast/svelte5/docs/runes/08-$props-id-input.svelte, tests/fixtures/parser/ast/svelte5/docs/runes/08-$props-id-output.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-$props-id-scope-output.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-$props-id-ts-input.svelte, tests/fixtures/parser/ast/svelte5/docs/runes/08-$props-id-ts-output.json, tests/fixtures/parser/ast/svelte5/docs/runes/08-$props-id-ts-scope-output.json
close: https://github.com/sveltejs/svelte-eslint-parser/issues/674
=> feat: support latest runes (`$props.id` and `$inspect.trace`)

.changeset/whole-sites-juggle.md, package.json
close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1114
=> fix: align required Node version with ESLint

.changeset/icy-pianos-film.md, src/parser/analyze-scope.ts, src/parser/index.ts, tests/fixtures/parser/ast/svelte5/$props-without-destructuring-runes-config.json, tests/fixtures/parser/ast/svelte5/$props-without-destructuring-runes-input.svelte, tests/fixtures/parser/ast/svelte5/$props-without-destructuring-runes-output.json, tests/fixtures/parser/ast/svelte5/$props-without-destructuring-runes-scope-output.json, tests/fixtures/parser/ast/svelte5/$props-without-destructuring-without-runes-config.json, tests/fixtures/parser/ast/svelte5/$props-without-destructuring-without-runes-input.svelte, tests/fixtures/parser/ast/svelte5/$props-without-destructuring-without-runes-output.json, tests/fixtures/parser/ast/svelte5/$props-without-destructuring-without-runes-scope-output.json
close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1159
close: https://github.com/sveltejs/eslint-plugin-svelte/issues/1158
=> fix: resolved issue of `$props` incorrectly detected as store when using variables named after runes like `$props` and `props`

src/parser/converts/block.ts
Spread is slower here than iterating through the converted children and pushing them individually.
Additionally, spreading the args can result in a large number of params which can cause other problems (sometimes `push` will throw).
I suspect the for loop is faster because `...convertChildren(...)` has to iterate the full set in order to allocate it to an array in memory, which it then has to iterate to spread as params. Whereas iterating through one at a time means we can add the child to the block without waiting for the entire iterable to finish.
i could be wrong, though. either way this fixes the rare edge case where you can try spread too many args to `push`
=> perf: iterate children using a for loop

benchmark/index.ts
In latest node, tsx/node seem to load this benchmark file as ESM which results in an error when trying to use `require.resolve`.
We can achieve the same with regular path resolution, using `import.meta` to get hold of the current path.
=> chore: drop require in benchmark

.changeset/gold-planes-retire.md, src/parser/typescript/analyze/index.ts, tests/fixtures/parser/ast/svelte5/$derived-in-template-with-ts01-input.svelte, tests/fixtures/parser/ast/svelte5/$derived-in-template-with-ts01-output.json, tests/fixtures/parser/ast/svelte5/$derived-in-template-with-ts01-scope-output.json, tests/fixtures/parser/ast/svelte5/$derived-in-template-without-ts01-input.svelte, tests/fixtures/parser/ast/svelte5/$derived-in-template-without-ts01-output.json, tests/fixtures/parser/ast/svelte5/$derived-in-template-without-ts01-scope-output.json
=> fix: crash with `$derived()` in template using ts
